### ISSUE TITLE
只能在腾讯云使用吗？

### ISSUE THREAD

**Issue by lx3238443k** [tencentyun/wafer2-node-sdk#19]

**Comment by jas0ncn** [comment]
可以参考我们的文档自行部署哈：
https://cloud.tencent.com/document/product/619/11445
https://cloud.tencent.com/document/product/619/12797

**Comment by lx3238443k** [comment]
不能配在阿里云里面吗？
如果不是腾讯的服务器的话，我们没有
   // 腾讯云相关配置可以查看云 API 秘钥控制台：https://console.cloud.tencent.com/capi
    'qcloudAppId' => 1200000000,// 必须是数字
    'qcloudSecretId' => '你的腾讯云 SecretId',
    'qcloudSecretKey' => '你的腾讯云 SecretKey',
    'networkTimeout' => 30000

**Comment by jas0ncn** [comment]
如果要使用万象优图、语音识别等腾讯云的功能，需要去控制台申请并配置，如果不是用，这里可以随便填，不为空即可。

**Comment by lx3238443k** [comment]
...thirdScriptError
Cannot read property 'connectUrl' of undefined;at pages/index/index openTunnel function;at api request success callback function
TypeError: Cannot read property 'connectUrl' of undefined
    at success (http://127.0.0.1:9973/appservice/vendor/wafer2-client-sdk/lib/tunnel.js:163:88)
    at callSuccess (http://127.0.0.1:9973/appservice/vendor/wafer2-client-sdk/lib/request.js:53:17)
    at Function.success (http://127.0.0.1:9973/appservice/vendor/wafer2-client-sdk/lib/request.js:103:33)
    at Object.success (http://127.0.0.1:9973/appservice/__dev__/WAService.js:3:11024)
    at s.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:8:24902)
    at s.emit (http://127.0.0.1:9973/appservice/__dev__/WAService.js:4:20239)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:8:26250)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:4:4315
    at a (http://127.0.0.1:9973/appservice/appservice:1014:7382)
    at b.<anonymous> (http://127.0.0.1:9973/appservice/appservice:1014:7469)

客户端上的报错...
请问配置里的 tunnelServerUrl 该怎么填写？...

**Comment by jas0ncn** [comment]
可以参考我们的文档自行部署哈：
https://cloud.tencent.com/document/product/619/11445
https://cloud.tencent.com/document/product/619/12797
